version: '3'

services:
  db:
    build:
      context: ./config/database
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
    restart: on-failure
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./config/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/database/data/:/var/lib/mysql/

  php:
    build:
      context: ./config/php-fpm
      args:
        - XDEBUG_REMOTE_HOST=${XDEBUG_REMOTE_HOST}
        - WITH_XDEBUG=${WITH_XDEBUG}
        - APP_ENV=${APP_ENV}
        - LOCAL_USER_ID=${LOCAL_USER_ID}
    depends_on:
      - db
    environment:
      - TZ=${TIMEZONE}
      - APP_ENV=${APP_ENV}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}?serverVersion=5.7
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - ./app/:/var/www/
      - ./config/php-fpm/composer-settings/:/home/proxy_user/.composer/
      - ./config/php-fpm/git-settings/.global_gitignore:/home/proxy_user/.global_gitignore
      - ${SSH_PRIVATE_KEY_PATH}:/home/proxy_user/.ssh/id_rsa
    user: ${LOCAL_USER_ID}
  nginx:
    build:
      context: ./config/nginx
      args:
        - HOST=${HOST}
    volumes:
      - ./app:/var/www
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - php
    environment:
      - TZ=${TIMEZONE}
    ports:
      - "80:80"
      - "443:443"
  adminer:
    image: adminer
    restart: on-failure
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce
    depends_on:
      - db
    ports:
      - 8080:8080


